image: barichello/godot-ci:3.4

pipelines:
  branches:
    master:
      - step:
          script:
            - mkdir build
            - godot -v --export "HTML5" build/index.html
          artifacts:
            - build/**
      - step:
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.7
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "us-east-1"
                S3_BUCKET: "jays-personal-projects-6969-420/simple-sweet/sprouts"
                EXPIRES: "2022-10-01"
                LOCAL_PATH: build
                ACL: "public-read"
