name: Export projects to HTML5 and deploy to S3 bucket
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.1.1

jobs:
  export-html5:
    name: Export projects to HTML5 and deploy to S3
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          apt update && apt upgrade
          apt install curl
          apt-get install unzip
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
          aws --version

      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync build/web/ s3://${{secrets.AWS_BUCKET_NAME}}/simple-sweet/sprouts --delete
